### PR TITLE
Use previous Trusty environment on Travis.

### PR DESCRIPTION
**Pull request by markrcote**
Support for Docker compose for local development.

### CODE REVIEW

**Comment by edmorley** [comment]
An alternative to rolling back the entire image is to install 3.6.14-1 of rabbitmq-server (see travis-ci/travis-cookbooks#954). This should already be installed in the image, so perhaps the entire install step can be removed.

**Comment by markrcote** [comment]
Hehe I was hoping to figure this out before you saw the PR. ;) Thanks, will try that!

**Comment by markrcote** [comment]
Well the setup works, but now there are (repeatable) test failures... will continue to investigate.

**Comment by markrcote** [comment]
Okay we're good now. :) The middle two commits were necessary to get this working on my local (Windows) environment. Not sure if they affected the tests or not, which seem to have failed only because of test timeouts (of course...). I bumped those timeouts up 10 times, from 3 seconds to 30.

**Comment by markrcote** [comment]
You can review this separately or as part of #35, as you wish.

**Pull request merged**
